  cscflow:
  image: node-red
  labels:
    io.rancher.scheduler.affinity:host_label: fname=host01
    io.rancher.container.start_once: 'true'
  expose:
   - 1880/tcp
  volume_driver: convoy-gluster
  volumes:
   - my_vol:/flowstudio
  environment:
    TOPIC: ${TOPIC}
    MESSAGE: ${MESSAGE}
    FLOW: "SravantiSVC"
