name: Srvanti Demo Service
description: |
  Sravanti's Demo Service
version: v0.0.1
category: Sravanti's Services
maintainer: Cisco
license: # The license
projectURL: # A URL related to the catalog entry
