cscflow:
  image: engci-docker.cisco.com:5932/flowstudio
  labels:
    io.rancher.scheduler.affinity:host_label: fname=host01
    io.rancher.container.start_once: 'true'
  expose:
   - 1880/tcp
  volume_driver: convoy-gluster
  volumes:
   - my_vol:/flowstudio
  environment:
    SEND_TO: ${SEND_TO}
    MESSAGE: ${SEND_MESSAGE}
    FLOW: "SENDEMAIL"
